# Generated by Django 5.1.6 on 2025-02-14 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.IntegerField(default=0)),
                ('classes_scheduled', models.IntegerField(default=0)),
                ('classes_taken', models.IntegerField(default=0)),
                ('workshops', models.IntegerField(default=0)),
                ('students_participated', models.IntegerField(default=0)),
                ('students_won', models.IntegerField(default=0)),
                ('course_referrals', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.trainer')),
            ],
        ),
    ]
