# Generated by Django 5.1.6 on 2025-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_trainer_designation_trainer_email_trainer_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerdata',
            name='score',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
